OBS_LIDAR_POINTS = 'lidar_points'
OBS_CAMERA_RGB_IMAGE = 'camera_image'
OBS_POSITION = 'player_pos'
OBS_ACTOR_EGO = 'ego_actor'
OBS_ACTORS_RAW = 'all_dynamic_actors'
OBS_OCCUPANCY_GRID = 'player_occupancy_grid'
OBS_GNSS_PREFIX = 'pos_gnss_'

ALIAS_EGO = 'ego'

INCREMENTAL_GRIDS = False

OCCUPANCY_RADIUS_DEFAULT = 5  # (5 and 15 or 10 and 9)
OCCUPANCY_TILE_LEVEL = 24
OCCUPANCY_BBOX_OFFSET = 0.1
OCCUPANCY_BBOX_HEIGHT = 3.5

LIDAR_ANGLE_DEFAULT = 15  # Caution: Choose Lidar angle depending on grid size
LIDAR_MAX_RANGE = 100
LIDAR_Z_OFFSET = 2.8

GNSS_Z_OFFSET = 2.8

RES_X = 1280
RES_Y = 720

N_PEDESTRIANS = 50

TOPIC_PREFIX_GRAPH_RAW_IN = '/graph_raw_in'
TOPIC_PREFIX_GRAPH_FUSED_OUT = '/graph_fused_out'

EDGE_DISTRIBUTION_TILE_LEVEL = 16
REMOTE_GRID_TILE_LEVEL = 19
